// <auto-generated />
namespace OnlineLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Exemple : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exemple));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130917246_Exemple"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
